global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-core'
    static_configs:
      - targets: ['as-nestjs:3000']

  - job_name: 'api-catalog'
    static_configs:
      - targets: ['as-fastapi:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['as-postgresql:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['as-redis:9121']

  - job_name: 'mongo'
    static_configs:
      - targets: ['as-mongodb:9216']